### ISSUE TITLE
Refactor docker structure

### ISSUE THREAD

**Issue by spitfiredd** [tubiomics/vulcan#14]
We want to refactor the `./docker/` directory so that when we add new image definitions we can easily build and deploy them.  We need to ensure that:

* that they match the `container` labels in nextflow processes
* update `push_image-dockerhub.yml` GitHub action

**Comment by tjyacoub** [comment]
Initial notes:
- We probably won't need to build and deploy all images in the `./docker/` folder every time a new image is added, and we likely won't have a high throughput of new docker images. So rather than building all based on the docker directory, we could have an argument that specifies exactly which images to build.

**Comment by tjyacoub** [comment]
Overview of docker image-related files in vulcan:

# I'm not sure if these are being used at all? 

- nextflow.config -> `process.container:"tubiomics/vulcan:latest`
- Makefile -> `docker build -t tubiomics/vulcan:latest`

# Mapping local docker files to docker hub container name

.gitub/push-image-dockerhub.yaml
  ` - dockerfile: docker/quality-control
   - name: vulcan-qc
`
# Location of dockerfiles

- `./docker/` 
   - amos
   - binning
   - quality-control

**Comment by spitfiredd** [comment]
@tjyacoub - you can remove those two lines, they were never removed from when I was trying to load all of the needed libraries and tools onto one docker image.

**Comment by tjyacoub** [comment]
More notes:

vulcan-mbpy2 is not being used

Strategy:
folder `./docker/metagenomic-binning/py3` --> name "vulcan-metagenomic-binning-py3"

program will check for uniqueness of name (there could be a potential conflict if there is another folder called `./docker/metagenomic/binning-py3`

python3 create-docker-yaml-file.py -dockerfile_paths /metagenomic-binning/py2
python3 create-docker-yaml-file.py -dockerfile_paths all


not being used:
 vulcan-gtdbtk
vulcan-mbpy2
